export default function Terms() {
  return (
    <div className="legal-page">
      <div className="legal-container">
        <h1>Terms and Conditions</h1>
        <p className="legal-updated"><strong>Last Updated: April 20, 2026</strong></p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using Superplot ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree, do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>Superplot is a private property management application that allows you to:</p>
        <ul>
          <li>Track and manage your real estate portfolio</li>
          <li>Store property documents in your personal Google Drive</li>
          <li>Search and organize property information</li>
          <li>Use AI-powered chat to ask questions about your documents and portfolio (Premium)</li>
          <li>Bring your own AI API key (BYOK) for AI features (Premium)</li>
        </ul>

        <h2>3. Account &amp; Authentication</h2>
        <ul>
          <li>You must sign in using a valid Google account</li>
          <li>You are responsible for maintaining the security of your Google account</li>
          <li>You must not share your account access with unauthorized individuals</li>
          <li>You must provide accurate information when using the Service</li>
        </ul>

        <h2>4. User Data &amp; Storage</h2>
        <ul>
          <li>Property data you enter is stored in our database, secured with Row Level Security</li>
          <li>Documents you upload are stored in <strong>your own Google Drive</strong>, not on our servers</li>
          <li>You retain full ownership of all your data and documents at all times</li>
          <li>We act only as a tool to organize and display your information</li>
        </ul>

        <h2>5. Google Drive Access</h2>
        <ul>
          <li>The Service requests limited access to your Google Drive via the <code>drive.file</code> scope</li>
          <li>We can only access files created by the Service within the "PropertyVault" folder</li>
          <li>We cannot read, modify, or delete any other files in your Google Drive</li>
          <li>You may revoke access at any time via your <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer">Google Account Permissions</a></li>
        </ul>

        <h2>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to gain unauthorized access to the Service or its systems</li>
          <li>Interfere with or disrupt the Service or its infrastructure</li>
          <li>Upload malicious files or content</li>
          <li>Use the Service to store content that violates any applicable laws</li>
        </ul>

        <h2>7. Intellectual Property</h2>
        <ul>
          <li>The Service and its original content, features, and functionality are owned by Superplot</li>
          <li>Your data and documents remain your property — we claim no ownership over user content</li>
        </ul>

        <h2>8. Availability &amp; Warranties</h2>
        <ul>
          <li>The Service is provided on an <strong>"as is"</strong> and <strong>"as available"</strong> basis</li>
          <li>We do not guarantee uninterrupted or error-free operation</li>
          <li>We make no warranties, express or implied, regarding the Service's reliability, accuracy, or fitness for a particular purpose</li>
          <li>We are not responsible for any data loss — you are encouraged to maintain your own backups</li>
        </ul>

        <h2>9. Limitation of Liability</h2>
        <p>To the fullest extent permitted by law:</p>
        <ul>
          <li>We shall not be liable for any indirect, incidental, special, consequential, or punitive damages</li>
          <li>We shall not be liable for any loss of data, profits, or business opportunities</li>
          <li>Our total liability shall not exceed the amount you paid for the Service (if any)</li>
        </ul>

        <h2>10. AI Features</h2>
        <ul>
          <li>AI features (chat, document analysis, portfolio intelligence) are available to Premium subscribers</li>
          <li>AI responses are generated by third-party language models and may not always be accurate</li>
          <li>AI output does <strong>not</strong> constitute legal, financial, or professional advice</li>
          <li>You should independently verify any AI-generated information before relying on it</li>
          <li>Document text is extracted, chunked, and stored as vector embeddings for AI retrieval</li>
        </ul>

        <h3>Bring Your Own Key (BYOK)</h3>
        <ul>
          <li>You may provide your own API key for Google Gemini, OpenAI, or Anthropic</li>
          <li>You are responsible for all usage charges incurred on your API key</li>
          <li>We store your key securely but are not liable for unauthorized use if your account is compromised</li>
          <li>You may delete your stored key at any time from Settings</li>
        </ul>

        <h2>11. Third-Party Services</h2>
        <p>The Service relies on third-party providers:</p>
        <ul>
          <li><strong>Google</strong> — Authentication and Drive storage</li>
          <li><strong>Supabase</strong> — Database and authentication infrastructure</li>
          <li><strong>Vercel</strong> — Application hosting</li>
          <li><strong>Google AI (Gemini)</strong> — AI chat, embeddings, and document OCR</li>
          <li><strong>OpenAI</strong> — AI fallback provider</li>
          <li><strong>Anthropic</strong> — AI fallback provider</li>
          <li><strong>Razorpay</strong> — Payment processing</li>
          <li><strong>Resend</strong> — Transactional email delivery</li>
        </ul>
        <p>We are not responsible for the availability, security, or practices of these third-party services. Your use of them is subject to their respective terms.</p>

        <h2>12. Account Termination</h2>
        <ul>
          <li>You may stop using the Service at any time</li>
          <li>You may revoke Google Drive access and delete your data at any time</li>
          <li>We reserve the right to suspend or terminate accounts that violate these Terms</li>
        </ul>

        <h2>13. Changes to Terms</h2>
        <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms. We will update the "Last Updated" date at the top of this page.</p>

        <h2>14. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.</p>

        <hr />
        <p className="legal-footer-note"><em>These terms apply to the Superplot application hosted at superplot.vercel.app.</em></p>
      </div>
    </div>
  );
}
